services:
  dev-habits:
    image: dev-habits
    build:
      context: .
      dockerfile: DevHabits.Api/Dockerfile
    ports:
      - "5202:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development