@DevHabits_Api_HostAddress = http://localhost:5202

GET {{DevHabits_Api_HostAddress}}/habits/
Accept: application/json

###
GET {{DevHabits_Api_HostAddress}}/habits/h_0198e275-784b-7735-ba6b-f3b722cf64ab
Accept: application/json

###
POST {{DevHabits_Api_HostAddress}}/habits/
Content-Type: application/json

{
  "name": "Solve Algorithm Problems",
  "description": "Solve at least one algorithm problem daily",
  "type": 0,
  "frequency": {
    "type": 1,
    "timesPerPeriod": 1
  },
  "target": {
    "value": 20,
    "unit": "pages"
  },
  "endDate": "2025-12-31",
  "milestone": {
    "target": 100,
    "current": 0
  }
}

###
PUT {{DevHabits_Api_HostAddress}}/habits/h_0198e275-784b-7735-ba6b-f3b722cf64ab
Content-Type: application/json

{
  "id": "h_0198e275-784b-7735-ba6b-f3b722cf64ab",
  "name": "Read Books 2",
  "description": "Read at least 20 pages daily 2",
  "type": 0,
  "frequency": {
    "type": 1,
    "timesPerPeriod": 1
  },
  "target": {
    "value": 20,
    "unit": "pages"
  },
  "endDate": "2025-12-31",
  "milestone": {
    "target": 100,
    "current": 0
  }
}

###
DELETE {{DevHabits_Api_HostAddress}}/habits/h_0198e275-784b-7735-ba6b-f3b722cf64ab
Accept: application/json
