@DevHabits_Api_HostAddress = http://localhost:5202

GET {{DevHabits_Api_HostAddress}}/tags/
Accept: application/json

###
GET {{DevHabits_Api_HostAddress}}/tags?sort=CreatedAt asc
Accept: application/json

###
GET {{DevHabits_Api_HostAddress}}/tags/t_0198e21f-457b-7959-a22c-b7ec0dbc7c40
Accept: application/json

###
POST {{DevHabits_Api_HostAddress}}/tags/
Content-Type: application/json

{
  "name": "Tag 1",
  "description": "Sample tag"
}

###
PUT {{DevHabits_Api_HostAddress}}/tags/t_0198e21f-457b-7959-a22c-b7ec0dbc7c40
Content-Type: application/json

{
  "id": "t_0198e21f-457b-7959-a22c-b7ec0dbc7c40",
  "name": "Tag 1",
  "description": "Sample tag 2"
}

###
DELETE {{DevHabits_Api_HostAddress}}/tags/t_0198e21f-457b-7959-a22c-b7ec0dbc7c40
Accept: application/json
