name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "9.x"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    strategy:
      fail-fast: false
      matrix:
        dotnet-version: [${{ env.DOTNET_VERSION }}]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore DevHabits.sln

      - name: Clean solution
        run: dotnet clean DevHabits.sln

      - name: Build solution
        run: dotnet build DevHabits.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test DevHabits.sln --configuration Release --no-restore --no-build --logger "trx;LogFileName=test-results.trx"

      - name: Publish artifacts
        run: dotnet publish DevHabits.sln --configuration Release --no-restore --no-build --output ./publish

#      - name: Upload test results
#        uses: actions/upload-artifact@v4
#        with:
#          name: test-results
#          path: DevHabits/TestResults/
#
#      - name: Upload published app
#        uses: actions/upload-artifact@v4
#        with:
#          name: published-app
#          path: DevHabits/publish/
